- name: variables practice
  hosts: local
  connection: local
  vars:
    COURSE: DevOps
    DURATION: 4 months
    TUTOR: Siva
  tasks:
    vars:
      COURSE: ansible
- name: print the course info
  ansible.builtin.debug:
    msg: " Course name is : {{ COURSE }}, Duration is {{ DURATION }}, trained by {{ TUTOR }} "