- name: conditions
  hosts: local
  connection: local

  vars_prompt:
    - name: NUMBER
      prompt: Enter a number
      private: false
      
  tasks:
  - name: check number is less than 10 or not
    ansible.builtin.debug:
      msg: " Given {{ NUMBER }} is less than 10 "
    when: NUMBER < 10
