- name: conditions
  hosts: local
  connection: local
  tasks:
  ansible.builtin.debug:
    msg: Enter a number {{ NUMBER }}
  ansible.builtin.debug:
    msg: Given {{ NUMBER }} is less than 10
  when: NUMBER < 10
