- name: check the facts
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check the os and install nginx if redhat
    ansible.builtin.dnf:
      name: nginx
      state: latest
    when: ansible_os_family == "redhat"
  - name: check the os and install nginx if redhat
    ansible.builtin.apt:
      name: nginx
      state: latest
    when: ansible_os_family == "debian"

